"""Added a StockNote model related to both the Stock model and the User model

Revision ID: 141fa696d3eb
Revises: 51de2bf32b75
Create Date: 2021-12-28 12:13:31.914929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141fa696d3eb'
down_revision = '51de2bf32b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_note_timestamp'), 'stock_note', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_note_timestamp'), table_name='stock_note')
    op.drop_table('stock_note')
    # ### end Alembic commands ###
