"""Added some timestamps to the model Stock

Revision ID: 2545cdf0b8a9
Revises: 584cc66d22de
Create Date: 2021-09-07 16:15:00.941236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2545cdf0b8a9'
down_revision = '584cc66d22de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('last_quote_update', sa.Float(), nullable=True))
    op.add_column('stock', sa.Column('quote_market_timestamp', sa.DateTime(), nullable=True))
    op.drop_index('ix_stock_timestamp', table_name='stock')
    op.create_index(op.f('ix_stock_last_quote_update'), 'stock', ['last_quote_update'], unique=False)
    op.create_index(op.f('ix_stock_quote_market_timestamp'), 'stock', ['quote_market_timestamp'], unique=False)
    op.drop_column('stock', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_stock_quote_market_timestamp'), table_name='stock')
    op.drop_index(op.f('ix_stock_last_quote_update'), table_name='stock')
    op.create_index('ix_stock_timestamp', 'stock', ['timestamp'], unique=False)
    op.drop_column('stock', 'quote_market_timestamp')
    op.drop_column('stock', 'last_quote_update')
    # ### end Alembic commands ###
