"""Added new columns to Stock for quote details

Revision ID: 2b89f4b66bae
Revises: ad573c0f8506
Create Date: 2021-11-25 10:56:49.919473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b89f4b66bae'
down_revision = 'ad573c0f8506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('quote_details_paylod', sa.Text(), nullable=True))
    op.add_column('stock', sa.Column('last_quote_details_update', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_stock_last_quote_details_update'), 'stock', ['last_quote_details_update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_last_quote_details_update'), table_name='stock')
    op.drop_column('stock', 'last_quote_details_update')
    op.drop_column('stock', 'quote_details_paylod')
    # ### end Alembic commands ###
