"""Added a new column to Stock for dividend yield

Revision ID: 51de2bf32b75
Revises: 2b89f4b66bae
Create Date: 2021-12-08 22:32:47.766548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51de2bf32b75'
down_revision = '2b89f4b66bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('dividend_yield', sa.Float(), nullable=True))
    op.create_index(op.f('ix_stock_dividend_yield'), 'stock', ['dividend_yield'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_dividend_yield'), table_name='stock')
    op.drop_column('stock', 'dividend_yield')
    # ### end Alembic commands ###
