"""Removed the market timestamp field from the Stock model

Revision ID: 5457a049284c
Revises: 2545cdf0b8a9
Create Date: 2021-09-09 16:02:20.340787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5457a049284c'
down_revision = '2545cdf0b8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_quote_market_timestamp', table_name='stock')
    op.drop_column('stock', 'quote_market_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('quote_market_timestamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_stock_quote_market_timestamp', 'stock', ['quote_market_timestamp'], unique=False)
    # ### end Alembic commands ###
