"""Added name and quote_payload to the Stock model

Revision ID: 584cc66d22de
Revises: c2f7afbe5931
Create Date: 2021-09-03 22:22:49.821835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584cc66d22de'
down_revision = 'c2f7afbe5931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('stock', sa.Column('quote_payload', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'quote_payload')
    op.drop_column('stock', 'name')
    # ### end Alembic commands ###
