"""Added a self referential one-to-many relationship to Post

Revision ID: 6031e0bef3a6
Revises: cbf67526c1a3
Create Date: 2022-01-19 21:54:20.779082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6031e0bef3a6'
down_revision = 'cbf67526c1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'post', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'parent_id')
    # ### end Alembic commands ###
