"""Added two fields in Stock for analyst estimates data

Revision ID: ad573c0f8506
Revises: e1af2c4cb653
Create Date: 2021-11-13 10:47:45.600856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad573c0f8506'
down_revision = 'e1af2c4cb653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('analyst_estimates_payload', sa.Text(), nullable=True))
    op.add_column('stock', sa.Column('last_analyst_estimates_update', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_stock_last_analyst_estimates_update'), 'stock', ['last_analyst_estimates_update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_last_analyst_estimates_update'), table_name='stock')
    op.drop_column('stock', 'last_analyst_estimates_update')
    op.drop_column('stock', 'analyst_estimates_payload')
    # ### end Alembic commands ###
