"""Added a couple of columns to the Stock model for financial history related data

Revision ID: c84d91b575bd
Revises: 183ae645c852
Create Date: 2021-10-11 21:56:25.269581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84d91b575bd'
down_revision = '183ae645c852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('last_financials_history_update', sa.DateTime(), nullable=True))
    op.add_column('stock', sa.Column('financials_history_payload', sa.Text(), nullable=True))
    op.create_index(op.f('ix_stock_last_financials_history_update'), 'stock', ['last_financials_history_update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_last_financials_history_update'), table_name='stock')
    op.drop_column('stock', 'financials_history_payload')
    op.drop_column('stock', 'last_financials_history_update')
    # ### end Alembic commands ###
