"""Initialized all existing tables

Revision ID: cbf67526c1a3
Revises: 
Create Date: 2022-01-16 10:22:31.195130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf67526c1a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('last_quote_update', sa.Float(), nullable=True),
    sa.Column('quote_payload', sa.Text(), nullable=True),
    sa.Column('last_financials_history_update', sa.DateTime(), nullable=True),
    sa.Column('financials_history_payload', sa.Text(length=16777215), nullable=True),
    sa.Column('last_quote_history_update', sa.DateTime(), nullable=True),
    sa.Column('analyst_estimates_payload', sa.Text(), nullable=True),
    sa.Column('last_analyst_estimates_update', sa.DateTime(), nullable=True),
    sa.Column('quote_history_payload', sa.Text(), nullable=True),
    sa.Column('quote_details_paylod', sa.Text(), nullable=True),
    sa.Column('last_quote_details_update', sa.DateTime(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_dividend_yield'), 'stock', ['dividend_yield'], unique=False)
    op.create_index(op.f('ix_stock_last_analyst_estimates_update'), 'stock', ['last_analyst_estimates_update'], unique=False)
    op.create_index(op.f('ix_stock_last_financials_history_update'), 'stock', ['last_financials_history_update'], unique=False)
    op.create_index(op.f('ix_stock_last_quote_details_update'), 'stock', ['last_quote_details_update'], unique=False)
    op.create_index(op.f('ix_stock_last_quote_history_update'), 'stock', ['last_quote_history_update'], unique=False)
    op.create_index(op.f('ix_stock_last_quote_update'), 'stock', ['last_quote_update'], unique=False)
    op.create_index(op.f('ix_stock_symbol'), 'stock', ['symbol'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_name'), 'notification', ['name'], unique=False)
    op.create_index(op.f('ix_notification_timestamp'), 'notification', ['timestamp'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('stock_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_note_timestamp'), 'stock_note', ['timestamp'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    op.create_table('watchers',
    sa.Column('watcher_id', sa.Integer(), nullable=True),
    sa.Column('watched_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['watched_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['watcher_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchers')
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_stock_note_timestamp'), table_name='stock_note')
    op.drop_table('stock_note')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_notification_timestamp'), table_name='notification')
    op.drop_index(op.f('ix_notification_name'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_table('message')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_stock_symbol'), table_name='stock')
    op.drop_index(op.f('ix_stock_last_quote_update'), table_name='stock')
    op.drop_index(op.f('ix_stock_last_quote_history_update'), table_name='stock')
    op.drop_index(op.f('ix_stock_last_quote_details_update'), table_name='stock')
    op.drop_index(op.f('ix_stock_last_financials_history_update'), table_name='stock')
    op.drop_index(op.f('ix_stock_last_analyst_estimates_update'), table_name='stock')
    op.drop_index(op.f('ix_stock_dividend_yield'), table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###
