"""Added two new columns to the Stock model for quote history data needs

Revision ID: e1af2c4cb653
Revises: c84d91b575bd
Create Date: 2021-11-07 12:04:09.871270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1af2c4cb653'
down_revision = 'c84d91b575bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('last_quote_history_update', sa.DateTime(), nullable=True))
    op.add_column('stock', sa.Column('quote_history_payload', sa.Text(), nullable=True))
    op.create_index(op.f('ix_stock_last_quote_history_update'), 'stock', ['last_quote_history_update'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_last_quote_history_update'), table_name='stock')
    op.drop_column('stock', 'quote_history_payload')
    op.drop_column('stock', 'last_quote_history_update')
    # ### end Alembic commands ###
